# Generated by Django 3.1.7 on 2021-03-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='timeatamp',
            new_name='timeastamp',
        ),
    ]
