# Generated by Django 3.1.7 on 2021-04-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210321_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('CODING', 'CODING'), ('GADGET', 'GADGET')], default='', max_length=255),
        ),
    ]
